### ISSUE TITLE
firmware builds with no errors but resulting zip makes the watch go into an error mode.

### ISSUE THREAD

**Issue by wanderling** [Emeryth/sma-q2-oss#15]
Error displayed on red screen:

`F:4001,0,200049DC`
`E:0x3`

Every now and then I get a brief flash of a blue screen with the word "Blue" about a third of the way down the screen then back to the error.
I can get back to the OTA mode using the Volume up + volume down + left button.

I have no background with nrf and middle of the road programming skills.

**Comment by Emeryth** [comment]
You might be hitting the bug where NVM storage (for pairing credentials) gets corrupted.
I've patched it now, flash the firmware and hold the OK button when restarting the watch.

**Comment by wanderling** [comment]
Perfect! You're a wizard! Now to try it out!

**Comment by wanderling** [comment]
I am unable to pair the Q2 with my phone either with the custom Gadgetbridge fork or from the Bluetooth menu on the phone. I have reset the Q2 several times as well as reflashed it with the working firmware.

The Q2 will show up immediately when placed back into OTA mode and disappear when rebooting into firmware.

I do apologize if I am missing something.

**Comment by Emeryth** [comment]
On your phone, make sure to delete Q2 from remembered devices.

**Comment by x29a** [comment]
Seems similar to #3, would be great if you could verify the fix!

Ive been there, and on one occasion, i had to disable secure pairing, see [this gist](https://gist.github.com/x29a/ebdea9acccca450119e1cc5b04dc36ac) for the relevant change.

**Comment by wanderling** [comment]
Okay, removed my other Q2 pairing (original firmware) on same phone. I can now see the new firmware on phone "sma-q2-oss", but gadgetbridge still doesn't. I am going to close this issue and rebuild gadgetbridge since the watch is working. As of this time I have not applied the change recommended by x29a. If rebuilding gadgetbridge fails to pick up the watch I will and get back with you. Thank you again!

**Comment by wanderling** [comment]
So, after rebuilding Gadgetbridge, I can now see and attempt to connect to the watch. When I try, however, the watch drops into the error screen mentioned in the beginning and eventually reboots. After applying the gist from x29a I can confirm all functions work!

**Comment by Emeryth** [comment]
Everything points to the flash storage problem I mentioned.
The latest patch should have fixed it.
Are you sure you did the reset correctly? Hold DOWN and OK (middle button) and then press BACK.
This completely erases the storage partition. The watch should pair successfully from that point on.

Removing secure pairing is just a workaround, all your notifications will be sent unecrypted over the air if you do it.

**Comment by wanderling** [comment]
Ah! I see. I will reverse the gist and try again. Thank you for that.
