### ISSUE TITLE
Pairing issue

### ISSUE THREAD

**Issue by x29a** [Emeryth/sma-q2-oss#6]
hi,

this is a very promising project and id like to contribute if possible, thanks for the great work!

i struggle to pair the sma q2 and various android phones (8.1.0) via the forked gadgetbridge, maybe you have a hint or two on how to get it working?

what i did:
- compile firmware (see PR #5)
- put watch into DFU mode and flash resulting firmware via D6Flasher
- compile forked gadgetbridge
- install generated debug apk via adb to phone (since the release version has no certificates)
- reboot phone
- try to add watch in gadgetbridge
- result: gadgetbridge never sees the sma q2

the bluetooth menu did see the watch and out of desperation i paired it with the phone directly. got asked to very the pins and paired it. unfortunately, gadgetbridge still didnt see the watch (i unchecked the option to hide paired devices).

now unfortunately, i deleted the pairing on the phone but then noticed, the watch will reject further pairing attempts right away.

as a last resort, i went back into DFU mode and reflashed the firmware. unfortunately, that did not restore the initial pairing capabilities.

do you have any tips from here on? 

id like to leave the watch closed if possible, but i could also open it to reach some jtag pins or whatever is needed.

thanks!

**Comment by Emeryth** [comment]
Sorry, looks like I forgot to write it down, but I did include a method to erase bonding information.

Hold DOWN and OK and then press BACK, this should reset the watch and erase bonding information.

**Comment by Emeryth** [comment]
And to properly pair with the watch I think you need to enable location access so Gadgetbridge can scan for BLE devices.

**Comment by x29a** [comment]
Thank you for your answer, i did find the reset combo by accident but didnt know it reset the watch totally so i havent tried re-pairing again. I can confirm that the phone was able to pair again (once) after resetting.

unfortunately, gadgetbridge cant find the SMA Q2, even when paired.

Is there a prebuilt version of the gadgetbridge fork somewhere i could try? or are you going to bring your changed upstream? i might have messed up something there.

Unfortunately, gadgetbridge is able to see the amazfit bip lite when its nearby, so it can access _some_ bluetooth information. double checked location and all other permissions, they are definately there.

Ill go and see if i can find another watch to try it out with. Any further hints greatly appreciated.

**Comment by x29a** [comment]
well, this is embarrassing. long story short: ensure that you cloned the forked GB repo and not the upstream one (it will see the watch but wont recognize it).

Then i had to perform a special "start GB search, pair watch manually via BT menu" and it worked :) 

Thanks!
